name: Branch Wise Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/**

jobs:
  dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running DEV pipeline"
  prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: run prod pipeline 
        run: echo "Running PROD pipeline"
      - name : print files
        run : ls -lrt 
      - name: Install Ansible
        run: sudo apt-get update 
             sudo apt-get update software-properties-common 
             sudo apt-get-add-repository ppa:ansible/ansible
             sudo apt-get install ansible              
      - name: Check Ansible Version
        run: ansible --version

  feature:
    if: startsWith(github.ref, 'refs/heads/feature/test-new')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running FEATURE pipeline"
