name: Branch Wise Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/**

jobs:
  dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running DEV pipeline"

  prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: run prod pipeline 
        run: echo "Running PROD pipeline"
      - name : print files
        run : ls -lrt

  feature:
    if: startsWith(github.ref, 'refs/heads/feature')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running FEATURE pipeline"
      - name : print files using feature pipeline
        run : ls -lrt
