---
- hosts: localhost
  become: yes
  tasks:
  - name: Create directory
    ansible.builtin.file:
        path: /home/mydirectory
        state: directory
        mode: '0755'
  - name: clone repo
    git: 
      repo: "https://github.com/sundhardevops/GitHub-Actions-test.git"
      dest: /home/mydirectory
      version: main
  - name: list repo folder
    command: ls /home/mydirectory
